=head1 MCC

A preprocessor to compile the C<Ma Tirelire> Palm OS project.

It allows to compile simili Objective-C to obfuscated but functionnal
C code. This simili Objective-C is not dynamic as the real one, it
only allows to have a thin object layer on top of C.

Palm OS is not able to run GNU Objective C because globals variables
are not allowed in all circumstances.

The F<Makefile> is a BSD one.

This stuff is known to work on FreeBSD L<http://FreeBSD.org>.

There is no support, so please don't ask.


=head1 INSTALLATION

You need to edit the F<Makefile> and change the C<PERLINC> variable to
your needs.

C<< perl -V | fgrep CORE >> can help you here...

You need to install L<Data::Alias> and L<Inline>.


=head1 LICENSE

Copyright 1996-2011, Maxime SoulE<eacute>

mcc may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.
